# Generated by Django 5.2.1 on 2025-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
