# Generated by Django 5.2.1 on 2025-05-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='telegram_chat_id',
        ),
    ]
